version: '3.8' # Specifies the docker-compose file format version

services:
  gmat_app: # This is the name of our service
    build: .
    image: gmat-diag-app:latest # Specifies the Docker image to use (the one we built earlier)
    container_name: gmat_diagnostic_container # Optional: gives a specific name to the running container
    ports:
      - "8502:8501" # Maps port 8502 of the host to port 8501 of the container
    restart: unless-stopped # Defines the restart policy
                           # unless-stopped: restarts the container unless it was explicitly stopped
                           # always: always restarts, even if stopped manually (use with caution)
                           # on-failure: restarts only if it exits with an error code
    volumes: # 持久化存儲 CSV 數據文件
      - ./gmat_diagnosis_app/student_subjective_reports.csv:/app/gmat_diagnosis_app/student_subjective_reports.csv
      - ./gmat_diagnosis_app/gmat_performance_data.csv:/app/gmat_diagnosis_app/gmat_performance_data.csv
    env_file:
      - .env
    environment: # Load environment variables from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MASTER_KEY=${MASTER_KEY} 
